services:
  xray:
    image: ghcr.io/xtls/xray-core:latest
    container_name: xray_vpn
    restart: unless-stopped
    command: run -c /etc/xray/config.json
    ports:
      - "443:443"
    volumes:
      - ./config.json:/etc/xray/config.json:ro
